/* This file was generated by pyxtract \n   Do not edit.*/

#ifdef _MSC_VER
    #define ORANGENE_EXTERN

    #ifdef ORANGENE_EXPORTS
        #define ORANGENE_API __declspec(dllexport)

    #else
        #define ORANGENE_API __declspec(dllimport)
        #ifdef _DEBUG
            #pragma comment(lib, "orangene_d.lib")
        #else
            #pragma comment(lib, "orangene.lib")
        #endif

    #endif // exports

    #define ORANGENE_VWRAPPER(x) \
        ORANGENE_EXTERN template class ORANGENE_API T##x; \
        ORANGENE_EXTERN template class ORANGENE_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;
   
    #define ORANGENE_WRAPPER(x) \
        class ORANGENE_API T##x; \
        ORANGENE_EXTERN template class ORANGENE_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;

#else
#ifdef DARWIN
    #define ORANGENE_API
    
    #ifdef ORANGENE_EXPORTS
        #define ORANGENE_EXTERN
    #else
        #define ORANGENE_EXTERN extern
    #endif

    #define ORANGENE_VWRAPPER(x) \
        typedef GCPtr< T##x > P##x;
 
    #define ORANGENE_WRAPPER(x) \
        class ORANGENE_API T##x; \
        typedef GCPtr< T##x > P##x;

#else // not _MSC_VER
    #define ORANGENE_API

    #ifdef ORANGENE_EXPORTS
        #define ORANGENE_EXTERN
    #else
        #define ORANGENE_EXTERN extern
    #endif

    #define ORANGENE_VWRAPPER(x) \
        ORANGENE_EXTERN template class ORANGENE_API T##x; \
        ORANGENE_EXTERN template class ORANGENE_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;
   
    #define ORANGENE_WRAPPER(x) \
        class ORANGENE_API T##x; \
        typedef GCPtr< T##x > P##x;

#endif
#endif

#define OGVWRAPPER ORANGENE_VWRAPPER
#define OGWRAPPER ORANGENE_WRAPPER
