/* This file was generated by pyxtract \n   Do not edit.*/

#ifdef _MSC_VER
    #define ORANGE_EXTERN

    #ifdef ORANGE_EXPORTS
        #define ORANGE_API __declspec(dllexport)

    #else
        #define ORANGE_API __declspec(dllimport)
        #ifdef _DEBUG
            #pragma comment(lib, "orange_d.lib")
        #else
            #pragma comment(lib, "orange.lib")
        #endif

    #endif // exports

    #define ORANGE_VWRAPPER(x) \
        ORANGE_EXTERN template class ORANGE_API T##x; \
        ORANGE_EXTERN template class ORANGE_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;
   
    #define ORANGE_WRAPPER(x) \
        class ORANGE_API T##x; \
        ORANGE_EXTERN template class ORANGE_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;

#else
#ifdef DARWIN
    #define ORANGE_API
    
    #ifdef ORANGE_EXPORTS
        #define ORANGE_EXTERN
    #else
        #define ORANGE_EXTERN extern
    #endif

    #define ORANGE_VWRAPPER(x) \
        typedef GCPtr< T##x > P##x;
 
    #define ORANGE_WRAPPER(x) \
        class ORANGE_API T##x; \
        typedef GCPtr< T##x > P##x;

#else // not _MSC_VER
    #define ORANGE_API

    #ifdef ORANGE_EXPORTS
        #define ORANGE_EXTERN
    #else
        #define ORANGE_EXTERN extern
    #endif

    #define ORANGE_VWRAPPER(x) \
        ORANGE_EXTERN template class ORANGE_API T##x; \
        ORANGE_EXTERN template class ORANGE_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;
   
    #define ORANGE_WRAPPER(x) \
        class ORANGE_API T##x; \
        typedef GCPtr< T##x > P##x;

#endif
#endif
