
/* from networkoptimization.hpp */
class EXPORT_DLL TNetworkOptimization;

/* from pathfinder.hpp */
class EXPORT_DLL TPathfinder;

/* from network.hpp */
class EXPORT_DLL TNetwork;

/* from mds.hpp */
class EXPORT_DLL TStressFunc;
class EXPORT_DLL TKruskalStress;
class EXPORT_DLL TSammonStress;
class EXPORT_DLL TSgnSammonStress;
class EXPORT_DLL TSgnRelStress;
class EXPORT_DLL TStressFunc_Python;
class EXPORT_DLL TMDS;

/* from graph_layout.hpp */
class EXPORT_DLL TGraphLayout;
