/* This file was generated by pyxtract \n   Do not edit.*/

#ifdef _MSC_VER
    #define ORANGEOM_EXTERN

    #ifdef ORANGEOM_EXPORTS
        #define ORANGEOM_API __declspec(dllexport)

    #else
        #define ORANGEOM_API __declspec(dllimport)
        #ifdef _DEBUG
            #pragma comment(lib, "orangeom_d.lib")
        #else
            #pragma comment(lib, "orangeom.lib")
        #endif

    #endif // exports

    #define ORANGEOM_VWRAPPER(x) \
        ORANGEOM_EXTERN template class ORANGEOM_API T##x; \
        ORANGEOM_EXTERN template class ORANGEOM_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;
   
    #define ORANGEOM_WRAPPER(x) \
        class ORANGEOM_API T##x; \
        ORANGEOM_EXTERN template class ORANGEOM_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;

#else
#ifdef DARWIN
    #define ORANGEOM_API
    
    #ifdef ORANGEOM_EXPORTS
        #define ORANGEOM_EXTERN
    #else
        #define ORANGEOM_EXTERN extern
    #endif

    #define ORANGEOM_VWRAPPER(x) \
        typedef GCPtr< T##x > P##x;
 
    #define ORANGEOM_WRAPPER(x) \
        class ORANGEOM_API T##x; \
        typedef GCPtr< T##x > P##x;

#else // not _MSC_VER
    #define ORANGEOM_API

    #ifdef ORANGEOM_EXPORTS
        #define ORANGEOM_EXTERN
    #else
        #define ORANGEOM_EXTERN extern
    #endif

    #define ORANGEOM_VWRAPPER(x) \
        ORANGEOM_EXTERN template class ORANGEOM_API T##x; \
        ORANGEOM_EXTERN template class ORANGEOM_API GCPtr< T##x >; \
        typedef GCPtr< T##x > P##x;
   
    #define ORANGEOM_WRAPPER(x) \
        class ORANGEOM_API T##x; \
        typedef GCPtr< T##x > P##x;

#endif
#endif

#define OMVWRAPPER ORANGEOM_VWRAPPER
#define OMWRAPPER ORANGEOM_WRAPPER
